// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function getFibonacci(number) {
  if (number < 3 && number > 0) {
    return number;
  } else {
    return getFibonacci(number - 2) + getFibonacci(number - 1)
  }
}

function getSumOfEvenFibonacci() {
  let sum = 0;
  for (let i = 2; getFibonacci(i) < 4000000; i += 2) {
    //console.log(getFibonacci(i));
    sum += getFibonacci(i);
  }
  return sum;
}

console.log(getSumOfEvenFibonacci());
